default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # list of supported hooks: https://pre-commit.com/hooks.html
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
      - id: check-docstring-first # checks a common error of defining a docstring after code
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang
      - id: check-shebang-scripts-are-executable # ensures that (non-binary) files with a shebang are executable
      - id: check-merge-conflict # checks for files that contain merge conflict strings
      - id: check-symlinks # checks for symlinks which do not point to anything
      - id: check-toml # checks toml files for parseable syntax
      - id: check-yaml # checks yaml files for parseable syntax
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source
      - id: detect-private-key # detects the presence of private keys
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      - id: mixed-line-ending # replaces or checks mixed line ending
      - id: name-tests-test # verifies that test files are named correctly
      - id: trailing-whitespace # trims trailing whitespace

  # collection of fast, cheap, regex based pre-commit hooks.
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-no-log-warn # quick check for the deprecated .warn() method of python loggers
      - id: python-use-type-annotations # enforce that python3.6+ type annotations are used instead of type comments

  # python code formatting
  - repo: https://github.com/psf/black
    rev: 24.1.1
    hooks:
      - id: black
        args: [--line-length, "120"]

  # python import sorting
  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]

  # python upgrading syntax to newer version
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  # python check (PEP8), programming errors and code complexity
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - "flake8-dunder-all" # ensures that modules have defined `__all__`
          - "flake8-class-attributes-order" # checks classes attributes order
          - "flake8-logging-format" # report string formatting inside logging
          - "flake8-print" # report print statements
          - "flake8-use-fstring" # report `%`-formatting and `str.format`
          - "flake8-rst-docstrings" # validate Python docstrings as reStructuredText
          - "flake8-pyproject" # flake8 plug-in loading the configuration from pyproject.toml
          - "flake8-annotations-coverage" # check that all types are annotated

  # python security linter
  - repo: https://github.com/PyCQA/bandit
    rev: "1.7.5"
    hooks:
      - id: bandit
        args: ["--config", "pyproject.toml"]
        additional_dependencies: [".[toml]"]

  # yaml formatting
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0-alpha.6
    hooks:
      - id: prettier
        types: [yaml]

  # word spelling linter
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        args:
          - --skip=data/**,logs/**,*.ipynb,*.bib,*.js
          - -L inout

  # python docstring formatting
  - repo: https://github.com/myint/docformatter
    rev: v1.7.4
    hooks:
      - id: docformatter
        args:
          [
            --in-place,
            --wrap-summaries=120,
            --wrap-descriptions=120,
            --style=sphinx,
            --black,
          ]

  # python docstring coverage checking
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0 # or master if you're bold
    hooks:
      - id: interrogate
        args: [-vv, --config=pyproject.toml, src/]
        pass_filenames: false

  # md formatting
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.16
    hooks:
      - id: mdformat
        args: ["--number"]
        additional_dependencies:
          - mdformat-gfm
          - mdformat-tables
          - mdformat_frontmatter
          - mdformat-toc
          - mdformat-black

  # shell scripts linter
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
